version: '3.8'

networks:
  markuppix.server.dev:
    name: server_internal_network
    driver: bridge

services:
  db:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: MarkupPixDB
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - markuppix.server.dev

  serverwebapi:
    container_name: markuppix-server
    build:
      context: .
      dockerfile: src/MarkupPix.Server.WebApi/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - markuppix.server.dev
  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - markuppix.server.dev
    
volumes:
  mysql_data: