//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkupPix.Core.Errors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarkupPix.Core.Errors.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when executing the user creation request.
        /// </summary>
        public static string MPX100 {
            get {
                return ResourceManager.GetString("MPX100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user with such an email already exists..
        /// </summary>
        public static string MPX101 {
            get {
                return ResourceManager.GetString("MPX101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during user registration..
        /// </summary>
        public static string MPX102 {
            get {
                return ResourceManager.GetString("MPX102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is empty..
        /// </summary>
        public static string MPX103 {
            get {
                return ResourceManager.GetString("MPX103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of users is empty..
        /// </summary>
        public static string MPX104 {
            get {
                return ResourceManager.GetString("MPX104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when executing a request to receive all users..
        /// </summary>
        public static string MPX105 {
            get {
                return ResourceManager.GetString("MPX105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user was not found..
        /// </summary>
        public static string MPX106 {
            get {
                return ResourceManager.GetString("MPX106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when receiving user data..
        /// </summary>
        public static string MPX107 {
            get {
                return ResourceManager.GetString("MPX107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating user data..
        /// </summary>
        public static string MPX108 {
            get {
                return ResourceManager.GetString("MPX108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating the document..
        /// </summary>
        public static string MPX200 {
            get {
                return ResourceManager.GetString("MPX200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A document with such an name already exists..
        /// </summary>
        public static string MPX201 {
            get {
                return ResourceManager.GetString("MPX201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document was not found..
        /// </summary>
        public static string MPX202 {
            get {
                return ResourceManager.GetString("MPX202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in receiving all documents..
        /// </summary>
        public static string MPX203 {
            get {
                return ResourceManager.GetString("MPX203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pages found for the document..
        /// </summary>
        public static string MPX204 {
            get {
                return ResourceManager.GetString("MPX204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while receiving the document..
        /// </summary>
        public static string MPX205 {
            get {
                return ResourceManager.GetString("MPX205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating document data..
        /// </summary>
        public static string MPX206 {
            get {
                return ResourceManager.GetString("MPX206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of pages does not match..
        /// </summary>
        public static string MPX207 {
            get {
                return ResourceManager.GetString("MPX207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when creating the page..
        /// </summary>
        public static string MPX208 {
            get {
                return ResourceManager.GetString("MPX208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document or page was not found..
        /// </summary>
        public static string MPX209 {
            get {
                return ResourceManager.GetString("MPX209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating the page..
        /// </summary>
        public static string MPX210 {
            get {
                return ResourceManager.GetString("MPX210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot reduce the number of pages..
        /// </summary>
        public static string MPX211 {
            get {
                return ResourceManager.GetString("MPX211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User data caching deserialization error..
        /// </summary>
        public static string MPX300 {
            get {
                return ResourceManager.GetString("MPX300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input parameter error.
        /// </summary>
        public static string MPX400 {
            get {
                return ResourceManager.GetString("MPX400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined error.
        /// </summary>
        public static string MPX500 {
            get {
                return ResourceManager.GetString("MPX500", resourceCulture);
            }
        }
    }
}
